// <auto-generated />
namespace InvoiceRegister.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class InvoiceRegisterDBv2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(InvoiceRegisterDBv2));
        
        string IMigrationMetadata.Id
        {
            get { return "202003120402254_InvoiceRegisterDB-v2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
